from matplotlib import pyplot as plt
import pandas as pd
import matplotlib

crude_oil_data = pd.read_csv("crude_oil_data_processed.csv")
crude_oil_data.describe()
crude_oil_data['Date'] = pd.to_datetime(crude_oil_data['Date'])
crude_oil_data.plot(x='Date', y='U.S. Crude Oil ', figsize=(12,8), color='brown')
plt.ylabel("Production")
plt.title('U.S. Crude Oil Production')
plt.show()
crude_oil_data.boxplot('California', figsize=(12,8))
plt.ylabel("Production")
plt.title('U.S. Crude Oil Production')
plt.show()
crude_oil_data[['Alaska', 'California']].boxplot(figsize=(12,8))
plt.ylabel('Production in Alaska, California')
plt.title('Alaska, California Crude Oil Production')
plt.show()
crude_oil_data.boxplot(column=['U.S. Crude Oil '], by=['Year'], figsize=(12,8))
plt.ylabel('Production')
plt.show()
year_data = crude_oil_data.groupby('Year', as_index=False).sum()
colors = ['C0','C1','C2','C3','C4','C5','C6','C7','C8','C9',]
year_data.plot.bar(x='Year', y='U.S. Crude Oil ', figsize=(12,8), color=colors,legend=False)
plt.ylabel('Production')
plt.xlabel('Year')
plt.title('US Crude Oil Production')
plt.show()
mean_prod_data=crude_oil_data.mean(numeric_only=True)[1:-3]
mean_prod_df = pd.DataFrame(mean_prod_data).reset_index()
mean_prod_df.columns = ['State' , 'Production']
plt.bar(mean_prod_df['State'], mean_prod_df['Production'],width=0.85)
plt.title('US Oil Mean Production June 2008 to June 2018')
plt.xticks(rotation=90)
plt.xlabel('State')
plt.ylabel('Production')
plt.show()
mean_prod_df['Production'].plot.kde(figsize=(12,18))
plt.show()