import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr, spearmanr
from sympy import rotations

bikesharing_data = pd.read_csv("bike_sharing_daily.csv", index_col=0)
bikesharing_data['dteday'] = pd.DatetimeIndex(bikesharing_data['dteday'])
bikesharing_data['temp'].corr(bikesharing_data['cnt'])
print(pearsonr(bikesharing_data['temp'], bikesharing_data['cnt']))
print(spearmanr(bikesharing_data['temp'], bikesharing_data['cnt']))
plt.figure(figsize=(12,8))
plt.scatter(bikesharing_data['temp'],bikesharing_data['cnt'], color='b')
plt.title('Bike Sharing Daily')
plt.xlabel('Temperature')
plt.ylabel('Count')
plt.show()
np.corrcoef(bikesharing_data['workingday'],bikesharing_data['registered'])
print(bikesharing_data.groupby('workingday').max()['registered'].plot(kind='bar',figsize=(12,8),color=['r', 'm']))
plt.title('Registered Users')
plt.ylabel('Count of Registered Users')
plt.show()
print(bikesharing_data.groupby('workingday').max()['casual'].plot(kind='bar',figsize=(12,8),color=['b', 'y']))
plt.title('Casual Users')
plt.ylabel('Count of Casual Users')
plt.show()
plt.figure(figsize=(12,8))
plt.scatter(bikesharing_data['windspeed'],bikesharing_data['registered'],color='m')
plt.xlabel('Windspeed')
plt.ylabel('Number of Registered Users')
plt.title('Registered Users Depending on Windspeed')
plt.show()
plt.figure(figsize=(12,8))
plt.matshow(bikesharing_data.corr(),fignum=False,aspect='equal',color='r')
columns = len(bikesharing_data.columns)
plt.xticks(range(columns),bikesharing_data.columns)
plt.yticks(range(columns),bikesharing_data.columns)
plt.colorbar()
plt.xticks(rotation=90)
plt.title('Correlations', y = 1.2)
plt.show()